{-
   Swagger Petstore
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Dog exposing (Dog, dogDecoder, dogEncoder)

import DateOnly exposing (DateOnly, dateOnlyDecoder, dateOnlyEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


type alias Dog =
    { id : Int
    , name : String
    , dateOfBirth : Maybe DateOnly
    , packSize : Maybe Int
    }


dogDecoder : Decoder Dog
dogDecoder =
    Decode.succeed Dog
        |> required "id" Decode.int
        |> required "name" Decode.string
        |> optional "dateOfBirth" (Decode.nullable dateOnlyDecoder) Nothing
        |> optional "packSize" (Decode.nullable Decode.int) Nothing



dogEncoder : String -> Dog -> Encode.Value
dogEncoder tag model =
    Encode.object
        [ ( "id", Encode.int model.id )
        , ( "name", Encode.string model.name )
        , ( "dateOfBirth", withDefault Encode.null (map dateOnlyEncoder model.dateOfBirth) )
        , ( "packSize", withDefault Encode.null (map Encode.int model.packSize) )
        , ( "type", Encode.string tag )
        ]

