{-
   Swagger Petstore
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Pet exposing (Pet, petDecoder, petEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


type alias Pet =
    { id : Int
    , name : String
    , tag : Maybe String
    }


petDecoder : Decoder Pet
petDecoder =
    Decode.succeed Pet
        |> required "id" Decode.int
        |> required "name" Decode.string
        |> optional "tag" (Decode.nullable Decode.string) Nothing



petEncoder : Pet -> Encode.Value
petEncoder model =
    Encode.object
        [ ( "id", Encode.int model.id )
        , ( "name", Encode.string model.name )
        , ( "tag", withDefault Encode.null (map Encode.string model.tag) )
        ]

