{-
   Swagger Petstore
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Error exposing (Error, errorDecoder, errorEncoder)

import DateTime exposing (DateTime, dateTimeDecoder, dateTimeEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


type alias Error =
    { code : Int
    , message : String
    , dateTime : Maybe DateTime
    }


errorDecoder : Decoder Error
errorDecoder =
    Decode.succeed Error
        |> required "code" Decode.int
        |> required "message" Decode.string
        |> optional "dateTime" (Decode.nullable dateTimeDecoder) Nothing



errorEncoder : Error -> Encode.Value
errorEncoder model =
    Encode.object
        [ ( "code", Encode.int model.code )
        , ( "message", Encode.string model.message )
        , ( "dateTime", withDefault Encode.null (map dateTimeEncoder model.dateTime) )
        ]

