{-
   Swagger Petstore
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.Pets exposing (createPets, listPets, showPetById)

import Data.Pets exposing (Pets, petsDecoder)
import Data.Error exposing (Error, errorDecoder)
import Dict
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "http://petstore.swagger.io/v1"


createPets : Http.Request ()
createPets =
    { method = "POST"
    , url = basePath ++ "/pets"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectStringResponse (\_ -> Ok ())
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


listPets : Http.Request Pets
listPets =
    { method = "GET"
    , url = basePath ++ "/pets"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson petsDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


showPetById : String -> Http.Request Pets
showPetById petId =
    { method = "GET"
    , url = basePath ++ "/pets/" ++ petId
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson petsDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request
